name: '🤖 Upstream Watcher'

on:
  schedule:
    - cron: '0 23 * * *'
  workflow_dispatch:

jobs:
  check:
    uses: Lanrenbang/.github/.github/workflows/reusable-upstream-watcher.yml@main
    with:
      repositories: |
        [
          {"repo": "a8m/envsubst"},
          {"repo": "joho/godotenv"}
        ]
      go_mod_deps: |
        [
          {"repo": "a8m/envsubst", "module": "github.com/a8m/envsubst"},
          {"repo": "joho/godotenv", "module": "github.com/joho/godotenv"}
        ]
    secrets:
      bot_pat: ${{ secrets.BOT_PAT }}
